In [29]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。

## 積の手計算

Aの１行目とBの1列目の積 
$$
    A_0{_0} B_0{_0} + A_0{_1}  B_1{_0}+ A_0{_2} B_2{_0}= 6
$$
Aの１行目とBの2列目の積 
$$
    A_0{_0} B_0{_1} + A_0{_1}  B_1{_1}+ A_0{_2} B_2{_1}= 29
$$
Aの１行目とBの3列目の積 
$$
    A_0{_0} B_0{_2} + A_0{_1}  B_1{_2}+ A_0{_2} B_2{_2}= -20
$$
Aの2行目とBの1列目の積 
$$
    A_1{_0} B_0{_0} + A_1{_1}  B_1{_0}+ A_1{_2} B_2{_0}= 12
$$
Aの2行目とBの2列目の積 
$$
    A_1{_0} B_0{_1} + A_1{_0}  B_1{_1}+ A_0{_2} B_2{_1}= 52
$$
Aの2行目とBの3列目の積 
$$
    A_1{_0} B_0{_2} + A_1{_1}  B_1{_2}+ A_1{_2} B_2{_2}= 38
$$
Aの3行目とBの1列目の積 
$$
    A_2{_0} B_0{_0} + A_2{_1}  B_1{_0}+ A_2{_2} B_2{_0}= -18
$$
Aの3行目とBの2列目の積 
$$
    A_2{_0} B_0{_1} + A_2{_1}  B_1{_1}+ A_2{_2} B_2{_1}= -51
$$
Aの3行目とBの3列目の積 
$$
    A_2{_0} B_0{_2} + A_2{_1}  B_1{_2}+ A_2{_2} B_2{_2}= -48
$$

３＊３の行列Cに求めた値を入れる
$$
    \boldsymbol{C} =
        \left[\begin{array}{c|cc}
            % 横並びは&を挟む
            6 & 29 & -20 \\
            12 & 52 & 38 \\
            -18 & -51 & -48 \\
        \end{array}\right] \quad
$$

# 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。

In [30]:
a = np.dot(a_ndarray, b_ndarray)
a

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [31]:
b = np.array(a_ndarray @ b_ndarray)
b

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [32]:
c = np.matmul(a_ndarray, b_ndarray)
c

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 【問題3】ある要素の計算を実装
np.matmul()やnp.dot()、または@演算子を使わずに、手計算で行った計算過程をNumPyによるスクラッチ実装で再現していきましょう。これにより、行列積の計算に対する理解を深めます。ここで考えるのは行列AとBのような次元が2の配列に限定します。

In [33]:
# 行列Cの各要素ごとの計算結果
a = a_ndarray
b = b_ndarray

for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        c = 0                                                   # Cの各要素を計算するためにcを初期化
        for k in range(b.shape[1]):
            c += a[i, k] * b[k, j]
        print(c)

6
29
-20
12
52
38
-18
-51
-48


# 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

In [49]:
def dot1(a,b):
    """
    parameter
    -------------------
    a: array
        行列A
    b: array
        行列B
    -------------------
    """
    n = a.shape[0]
    m = a.shape[1]# 行列Aの列の数
    l = b.shape[1]# 行列Bの列の数
    r = np.empty((n, l))#　空の行列Cを作成
    for i in range(n):
        for j in range(l):
            c=0.0
            for k in range(m):
                c+=a[i,k]*b[k,j]
            r[i,j]= c 
    return r

In [35]:
dot1(a_ndarray, b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

# 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [36]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [51]:
def dot2(a,b):
    n = a.shape[0]
    m= a.shape[1]
    l = b.shape[1]
    o = b.shape[0]#　行列bの行の数
    
    # aの列数とbの行数が同じか判定
    if m == o: 
        r = np.empty((n, l))
        for i in range(n):
            for j in range(l):
                c=0.0
                for k in range(m):
                    c+=a[i,k]*b[k,j]
                r[i,j]= c 
        return r
    else:
        print('この行列積はサイズが違うので計算できません')

In [52]:
dot2(d_ndarray, e_ndarray)

この行列積はサイズが違うので計算できません


# 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。

np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [39]:
dot2(d_ndarray, e_ndarray.T)

array([[ 46.,  -4.],
       [-34.,  73.]])