# 【問題1】これまで利用してきたクラスの列挙
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。

Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

<strong>[answer]</strong><br>
Pandas:
    DataFrame<br>
matplotlib:
    pyplot<br>
scikit-learn:
    LinearRegression<br>
    

# 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。

最低でもそれぞれ5つ以上答えてください。

<strong>[answer]</strong><br>
- isnull()
- join()
- head()
- describe()
- value_counts()

# 【問題3】標準化クラスをスクラッチで作成
理解をより深めるため、StandardScalerをスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。

今回は雛形を用意しました。クラスの作成方法は関数に近いです。メソッドはクラスの中にさらにインデントを一段下げて記述します。

インスタンス変数を作成する際はself.mean_のようにselfを付けます。クラスの外からscaler.mean_と書いていたscalerの部分が自分自身を表すselfになっています。

In [34]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """
        self.X = X
        self.mean_ =  sum(X) / len(X)
        self.var_ = sum((X - sum(X) / len(X))**2 ) / (len(X) - 1)
        pass

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_) / np.sqrt(self.var_) #sqrt　：　平方根
        return X_scaled

In [35]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris


data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.08488889 0.09433333 0.01166667 0.00622222]
[[ 0.82373177  0.6186158  -0.46291005 -0.25354628]
 [ 0.13728863 -1.00932052 -0.46291005 -0.25354628]
 [-0.54915451 -0.35814599 -1.38873015 -0.25354628]
 [-0.89237609 -0.68373326  0.46291005 -0.25354628]
 [ 0.4805102   0.94420307 -0.46291005 -0.25354628]
 [ 1.85339649  1.92096486  2.31455025  2.28191649]
 [-0.89237609  0.29302854 -0.46291005  1.01418511]
 [ 0.4805102   0.29302854  0.46291005 -0.25354628]
 [-1.57881923 -1.33490779 -0.46291005 -0.25354628]
 [ 0.13728863 -0.68373326  0.46291005 -1.52127766]]


# 【問題4】 四則演算を行うクラスの作成
上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。

コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。

クラス名や説明文も適切に書き換えてください。

In [68]:
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
        
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
    
    def sub(self, value3):
        """
        受け取った引数をself.valueから引く
        """
        self.value -= value3
        
    def mul(self, value4):
        """
        受け取った引数をself.valueにかける
        """
        self.value *= value4
        
    def div(self, value5):
        """
        受け取った引数をself.valueを割る
        """
        self.value /= value5

        
        
example = ExampleClass(6)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.sub(3)
print("value : {}".format(example.value))
example.mul(3)
print("value : {}".format(example.value))
example.div(3)
print("value : {}".format(example.value))

初期値6が設定されました
value : 6
value : 9
value : 6
value : 18
value : 6.0
